### ISSUE TITLE
Criar Spike: pacote simples de python pip

### ISSUE THREAD

**Issue by brunomartins03** [fga-eps-mds/2022-2-ez-docs#13]

**Comment by diogjunior100** [comment]
PacotePip Teste criado e funcionando corretamente.
pip install pacotepip==0.0.1

https://pypi.org/project/pacotepip/0.0.1/
https://github.com/diogjunior100/pacotepip

**Comment by igorpenhaa** [comment]
O pacote pip teste criado, ainda não é o final do projeto, esse pacote foi criado com finalidade de aprendizagem para que no futuro não haja complicações no projeto.
