### ISSUE TITLE
Documentação inicial de arquitetura

### ISSUE THREAD

**Issue by brunomartins03** [fga-eps-mds/2022-2-ez-docs#14]

**Comment by RafaelN0bre** [comment]
![image](https://user-images.githubusercontent.com/71106783/203624084-9d519b23-55e0-468f-b1af-8ca16417f906.png)
![image](https://user-images.githubusercontent.com/71106783/203624092-ccbb24dc-fa3e-41eb-964e-dc031c334787.png)
![image](https://user-images.githubusercontent.com/71106783/203624112-1965be95-bd47-4fec-bb11-a39f081f9838.png)

Este é o esboço de arquitetura primário, da definição dos módulos
