### ISSUE TITLE
Primeira semana de treinamentos em python

### ISSUE THREAD

**Issue by brunomartins03** [fga-eps-mds/2022-2-ez-docs#2]
<h1>Descrição</h1>
Agora que o tema do projeto foi definido com sucesso, utilizaremos a primeira semana para (re)aprender a linguagem Python, cuja qual foi escolhida como base de nosso código.

<h1>Tarefas</h1>

- [x] Dominar o básico da linguagem Python: números, strings, listas, dicionários, sets, funções, laços de repetição, estruturas condicionais, etc.
- [x] Alcançar nível igual ou superior a 5 no ([Checkio](https://py.checkio.org/)) para python, postando, na sequência, o link do perfil do Checkio nesta mesma issue.

<h1>Critérios de aceitação</h1>

- [x] Nível do perfil Checkio igual ou superior a 5.

**Comment by BrunoRiibeiro** [comment]
https://py.checkio.org/user/BrunoRiibeiro/

**Comment by igorpenhaa** [comment]
começando o checkio!

**Comment by RochaCarla** [comment]
Sugestão próxima semana:
pandas


olhar https://github.com/luanguimaraesla/pandocker

**Comment by LucasBergholz** [comment]
https://py.checkio.org/user/LucasBergholz/
Nível 5 alcançado.

**Comment by RafaelN0bre** [comment]
https://py.checkio.org/user/RafaelNobre00/
Nível 5 alcançado

**Comment by diogjunior100** [comment]
https://py.checkio.org/user/diogjunior100/
Nível 5 alcançado

**Comment by brunomartins03** [comment]
https://py.checkio.org/user/bruno.martval/

**Comment by igorpenhaa** [comment]
https://py.checkio.org/user/Penharolis/
Tinha esquecido de postar, mas Nível 5 alcançado.
