### ISSUE TITLE
Decisão para reuniões semanais da equipe

### ISSUE THREAD

**Issue by brunomartins03** [fga-eps-mds/2022-2-ez-docs#3]
<h1>Reuniões semanais</h1>
<p>Comentem abaixo, por favor, quais são seus melhores dias e horários para realizarmos uma reunião semanal (provavelmente online).</p>
<p>Calculo que, devido ao tamanho do projeto, os encontros durarão <strong>não mais que 20 minutos</strong>.</p>

**Comment by BrunoRiibeiro** [comment]
acredito q podemos fazer depois das aulas, presencial msm

**Comment by igorpenhaa** [comment]
Gosto muito da ideia das reuniões pós aula, pois já estaríamos reunidos em um mesmo local e para mim o debate presencial funciona melhor até mesmo para compreensão  do que será discutido.

**Comment by diogjunior100** [comment]
Reuniões após a aula seria uma boa. No meu caso, eu não tenho aula depois das 12 horas. Além disso, um debate presencial pode funcionar melhor do que uma reunião online.
