### ISSUE TITLE
Implementação do pacote pip

### ISSUE THREAD

**Issue by RafaelN0bre** [fga-eps-mds/2022-2-ez-docs#30]
# Pacote pip

Desenvolver pacote pip para o módulo gera_documentos que está na devel. Já subir, permitir que seja instalado pelo terminal com pip install, e executar o __init__.py a partir da linha de comando, passando o nome do módulo e os parâmetros de entrada.

## Critérios de aceitação

- [x] pacote pip publicado e permitindo instalação com pip install
- [x] poder ser executado via linha de comando ,uma vez instalado pelo pip
- [x] executar o main do __initi.py__ com a passagem de parâmetros no terminal

**Comment by diogjunior100** [comment]
Pacote pip já está disponível para ser instalado pelo terminal. Falta apenas atualizar certas funcionalidades que ainda não foram finalizadas no projeto (Ex: README.md incompleto)
