### ISSUE TITLE
Finalização do pacote pip

### ISSUE THREAD

**Issue by RafaelN0bre** [fga-eps-mds/2022-2-ez-docs#43]
# Descrição

O pacote pip precisa ser disponibilizado, a fim de permitir download via CLI em qualquer ambiente Python.

**Nome final** : mkdocs-s7

## Critérios de aceitação

- [x] Possibilidade de instalar o pacote via CLI
- [x] Testes em ambiente linux, windows, conda, env...
- [x] Execução do comando via CLI
- [x] Execução correta de todos as possibilidades
- [x] Uso das flags --help e --about

**Comment by diogjunior100** [comment]
Pip está funcional, rodando em ambiente windows, conda, env.
Instalação e execução através do CLI.
Uso de flags não está totalmente concluído
