### ISSUE TITLE
Pacotes do python (pip)

### ISSUE THREAD

**Issue by brunomartins03** [fga-eps-mds/2022-2-ez-docs#5]
<h1>Descrição</h1>
<p>Utilizar semana para pesquisar sobre os pacotes do Python (pip): o que são, como funcionam, como criá-los e atualizá-los. Realizar testes.</p>
<h1>Tarefas</h1>

- [x] Pesquisar sobre pacotes pip do Python.
- [x] Realizar testes, se possível.

<h1>Critérios de Aceitação</h1>
<p>Enviar resumos e link úteis nesta issue.</p>

**Comment by diogjunior100** [comment]
Links de Referência:
https://medium.com/data-hackers/pypi-publicando-seu-primeiro-pacote-de7eb75db452
http://pythonclub.com.br/como-distribuir-sua-aplicacao-python-com-pypi.html

**Comment by RafaelN0bre** [comment]
[Deploy A Python Package To PyPI](https://initialcommit.com/blog/Deploy-Python-Package-PyPI#:~:text=Deploying%20a%20Package%20to%20PyPI%20The%20first%20step,the%20outputs%20in%20a%20new%20folder%20called%20%2Fdist.)

**Comment by diogjunior100** [comment]
Tutorial: Criação Pacote Pip
[Pip-Documentacao.pdf](https://github.com/fga-eps-mds/2022-2-Squad07/files/10027020/Pip-Documentacao.pdf)
