### ISSUE TITLE
Arquitetura de software, documentação e organização

### ISSUE THREAD

**Issue by brunomartins03** [fga-eps-mds/2022-2-ez-docs#6]
<h1>Descrição</h1>
<p>Utilizar semana para estudar arquitetura de software, documentação de projeto e organização do repositório (branches, issues, commits, etc).</p>
<h1>Tarefas</h1>

- [x] Estudar o básico de arquitetura de software.
- [x] Estudar sobre documentação de projeto.
- [x] Pesquisar sobre organização do repositório.

<h1>Critérios de Aceitação</h1>
<p>Enviar pequeno resumo até o final da sprint atual (22/11).</p>

**Comment by RafaelN0bre** [comment]
Primeiro template da modularização possível do projeto:
![image](https://user-images.githubusercontent.com/71106783/203569702-619365a6-c5c3-45da-8ae1-d2ee672a6c30.png)
