### ISSUE TITLE
Incremento do README

### ISSUE THREAD

**Issue by RafaelN0bre** [fga-eps-mds/2022-2-ez-docs#64]
# Descrição

Como recomendação da professora, é necessário adaptar o README do projeto, de acordo com a documentação apresentada por ela:

O que precisa :
## Descrição
Resumo do que foi feito na primeira release
#### Funcionalidades
- Lista das funcionalidades entregues (com a issue relacionada)
- Lista de artefatos realizados (docs feitos)
#### Bugs Mapeados
- O que vcs encontraram de problemas e precisam resolver na r2 

[link da mensagem](https://t.me/c/1861382048/207)

## Critérios de Aceitação
- [x] README atualizado e seguindo padrão de projeto de software
- [x] Branch e pull request

**Comment by BrunoRiibeiro** [comment]
Concluído
