### ISSUE TITLE
# Lançamento e Deploy da versão 1 do pacote

### ISSUE THREAD

**Issue by RafaelN0bre** [fga-eps-mds/2022-2-ez-docs#65]
# Descrição

Issue destinada ao lançamento da versão 1.0.0 do pacote ez-docs dentro do sistema de distribuição python PyPI

## Critérios de Aceitação

- [x] Pacote atualizado dentro do PyPI
- [x] Testes executados em ambientes linux e windows, com instalação e utilização do pacote
- [x] Verificação de todos os documentos (README, LICENCE . . . )
- [x] Branch e pull request

**Comment by diogjunior100** [comment]
Pip ez-docs 1.0.0 lançado para a release 1.
https://pypi.org/project/ez-docs/
