### ISSUE TITLE
Levantar bibliotecas para envio de e-mail em python

### ISSUE THREAD

**Issue by RafaelN0bre** [fga-eps-mds/2022-2-ez-docs#82]
# Descrição

Elencar bibliotecas para envio de e-mails em python

## Critérios de Aceitação
- [ ] Descrever nos comentários link de bibliotecas
- [ ] Responder à questão : Usaremos um email próprio ou solicitaremos o do usuário?
- [ ] Realizar testes, criando uma função que recebe um nome, email e documento e faz o envio.

**Comment by BrunoRiibeiro** [comment]
posso ajudar nesssa issue

**Comment by RafaelN0bre** [comment]
There are several libraries in Python that can be used to send email. Some popular ones include:

smtplib: This is a built-in library in Python for sending emails using the Simple Mail Transfer Protocol (SMTP).
yagmail: This is a simple and easy-to-use library for sending emails using Gmail as the mail server.
Flask-Mail: This is a Flask extension that provides simple integration with the email functionality of your application.
email: This is a built-in library in Python for creating and parsing email messages.
envelopes: A tiny python library for sending emails.
These are some examples, and you can always find other libraries depending on your requirements, and you can research on the best library that fit your usecase.

**Comment by BrunoRiibeiro** [comment]
exemplo de lib e como utilizar:
https://youtu.be/OLrC4J2-pvk

**Comment by RafaelN0bre** [comment]
A pesquisa foi suficiente para destacar que o envio de e-mail não se aplica ao projeto, de modo que  envio de e-mails, sem a utilização de um SMTP de terceiro, precisaria de etapas de autenticação que não podem ser realizadas. Portanto, iremos focar em resolver os bugs, adicionar novas features, implementar o CI e a cobertura de testes;
