### ISSUE TITLE
CI/CD - Pipeline

### ISSUE THREAD

**Issue by RafaelN0bre** [fga-eps-mds/2022-2-ez-docs#83]
# Descrição

Pesquisar métodos para setar o CI e CD no girthub
Somente será feito CI/CD com a branch main:

**Prioridades**:
- Lançar versão nova do pacote python no PyPi

**Secundários**
- Estágio de testes unitários (cobertura mínima de 70%)
- Verificação de codestyle

## Critérios de Aceitação
- [x] Comentários com link de artigos e exemplos de como realizar os objetivos
- [ ] Spikes de testes

**Comment by brunomartins03** [comment]
Links de referência:
[What is CI/CD?](https://www.redhat.com/en/topics/devops/what-is-ci-cd)
[Setting up CI/CD for Python Packages using GitHub Actions](https://www.section.io/engineering-education/setting-up-cicd-for-python-packages-using-github-actions/l)

**Comment by diogjunior100** [comment]
OK! Vou analisar o conteúdo dos links

> Links de referência: [What is CI/CD?](https://www.redhat.com/en/topics/devops/what-is-ci-cd) [Setting up CI/CD for Python Packages using GitHub Actions](https://www.section.io/engineering-education/setting-up-cicd-for-python-packages-using-github-actions/l)

**Comment by diogjunior100** [comment]
Link Referência:
https://github.blog/2022-06-03-a-beginners-guide-to-ci-cd-and-automation-on-github/

**Comment by brunomartins03** [comment]
A pipeline está parcialmente completa. Encontramos alguns bugs no que tange ao incremento automático da versão quando há a execução do workflow no github actions. Tentamos usar pacotes python auxiliares, mas sem sucesso.
A etapa secundária de desenvolvimento da pipeline ocorrerá na sprint seguinte.
