### ISSUE TITLE
Debug & melhoramento

### ISSUE THREAD

**Issue by brunomartins03** [fga-eps-mds/2022-2-ez-docs#89]
# Descrição
Debug do código fonte.

**Prioridades**:
- [x] Encontrar bugs nos módulos (data_cleaning, doc_generator, usable, etc) e na main através de variados casos de teste utilizando o pytest ou qualquer outra biblioteca que acharem útil ou necessária;
- [x] Propor soluções para eliminação dos bugs encontrados;
- [x] Reportar à equipe caso seja preciso realizar uma grande mudança de código; 

## Critérios de Aceitação
- [x] Commits e pull request com descrição das atividades desenvolvidas.

**Comment by LucasBergholz** [comment]
Major breaking news just discovored. The folders setup has changed in a way that the imports on some files aren't working anymore. More specificaly, the ez_docs folder changed it's path in one random commit. Thankfully, me and the team (Igor and Bruno Ribeiro) found this problem before we launched a package with breaking problems inside it.
