### ISSUE TITLE
Definição dos requisitos funcionais e não funcionais do sistema

### ISSUE THREAD

**Issue by brunomartins03** [fga-eps-mds/2022-2-ez-docs#9]
<h1>Requisitos funcionais e não funcionais do sistema</h1>
<p>Comentem abaixo quais requisitos vocês acham que são fundamentais para o nosso projeto, focando na <strong>Release 1(R1)</strong>.</p>
<p><strong>Atenção:</strong> A R1 está programada para acontecer no dia 13/12/22 (MENOS DE 1 MÊS!!!!).</p>

**Comment by brunomartins03** [comment]
Requisitos Funcionais
1) Gerar pdf de documentos (certificados, declarações, currículos, recibos) a partir de um template e uma database.
2) Enviar o pdf por email.

Requisitos não funcionais
1) Filtrar dados antes de gerar o pdf em si (por exemplo, ver se todos os campos de uma coluna estão preenchidos).
2) Ser instalável via pip.

**Comment by BrunoRiibeiro** [comment]
Requisitos não funcionais

  1. seleção via Vi de linhas há serem (ou não) usadas na confecção do documento.
  ex:
       1 Bruno Ribeiro   | II    | dd/MM/yyyy
       2 Bruno Martins  | SS  | dd/MM/yyy
       3 Rafael Nobre    | MS | dd/MM/yyy
       4 Igor Penha       | MM | dd/MM/yyy

       : 2-4

  Assim seriam feitos apenas das linhas 2, 3, 4

**Comment by igorpenhaa** [comment]
Acredito que para um MVP, os requisitos funcionais deveriam ser como o Bruno Martins disse, gerar o pdf do documento e enviar para seu respectivo email.
